# Generated by Django 5.1.7 on 2025-03-22 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PictureModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('caption', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('picture_url', models.URLField()),
            ],
        ),
    ]
