# Generated by Django 5.0.14 on 2025-04-22 15:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pictures_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="picturemodel",
            name="caption",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="picturemodel",
            name="location",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
